baseURL = "https://hover.build/"
languageCode = "en-us"
title = "Hover"
theme = "kube"
description = "Hover brings Flutter apps to the desktop."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "GeertJohan"
  github = "GeertJohan"
  twitter = "GeertJohan"
  email = "gjr19912+hover-dot-build@gmail.com"

[[menu.main]]
    name = "Blog"
    weight = -400
    url = "/blog/"
[[menu.main]]
    name = "Docs"
    weight = -300
    url = "/docs/"
[[menu.main]]
    name = "Faq"
    weight = -200
    url = "/faq/"
[[menu.main]]
    name = "GitHub"
    weight = -100
    url = "https://github.com/go-flutter-desktop/hover"
